export const projectsData = [
  {
    id: 'cook-some-hooks',
    title: 'Cook some hooks',
    description: 'A v4 hook generator leveraging generative AI where users can select a pair, introduce a prompt, get the hook generated, deployed and verified in a couple clicks.',
    emoji: '👨‍🍳',
    externalLink: 'https://ethglobal.com/showcase/cook-some-hooks-9e8yv',
    hackathon: 'ETH Global Brussels',
    award: 'Finalist top 10 project',
    date: 'July 2024',
  },
  {
    id: 'popkorn',
    title: 'POPKORN',
    description: 'A solution for proving private key ownership without signatures, simplifying wallet verification by removing traditional proof requirements.',
    emoji: '🍿',
    githubLink: 'https://github.com/private-key-black-box/frontend',
    externalLink: 'https://devfolio.co/projects/popkorn-61b7',
    hackathon: 'zkKrakow',
    award: '1st place Mina',
    date: 'May 2024',
  },
  {
    id: 'endorsis',
    title: 'Endorsis',
    description: 'A private platform for managing event feedback, offering a secure and user-friendly interface for gathering and analyzing responses.',
    emoji: '📝',
    githubLink: 'https://github.com/Endorsis/Endorsis',
    externalLink: 'https://demo-starter-frontend-git-fronttanguy-cleanerzkps-projects.vercel.app/#/',
    hackathon: 'ETHDam\'24',
    award: 'Oasis grant recipient',
    date: 'April 2024',
  },
  {
    id: 'spot-instance-comparison',
    title: 'Spot Instance Price Comparison',
    description: 'An automated tool for collecting and comparing spot pricing data from major cloud providers to optimize infrastructure spending.',
    emoji: '💰',
    githubLink: 'https://github.com/cleanerzkp/spot-instance-comparison',
    hackathon: 'Client project',
    date: 'Feb 2024',
  },
  {
    id: 'ghoflow',
    title: 'GhoFlow',
    description: 'A payment widget and smart contracts to simplify the creation of superfluid streams of GHO tokens, reducing the number of transactions needed.',
    emoji: '💸',
    externalLink: 'https://ethglobal.com/showcase/ghoflow-e8y2c',
    hackathon: 'LFGHO - async hackathon',
    date: 'Jan 2024',
  },
  {
    id: 'dog',
    title: 'DOG (Def Original Goal)',
    description: 'Uncollateralized micro credits protocol based on a credit scored built using ZK proofs of peoples on and off-chain reputation.',
    emoji: '🐶',
    githubLink: 'https://github.com/0xPetra/zkCreditScore',
    externalLink: 'https://ethglobal.com/showcase/dog-gipja',
    hackathon: 'ETHGlobal Istanbul',
    award: 'Best use of Threshold',
    date: 'Nov 2023',
  },
  {
    id: 'rebuilddao',
    title: 'RebuildDAO',
    description: 'A DAO project allowing Romans to vote on which parts of the city should be renovated and manage local budgets on-chain. A proof-of-concept for decentralized urban planning and budget management.',    emoji: '🏛️',
    githubLink: 'https://github.com/orgs/RebuildDAO/repositories',
    externalLink: 'https://rebuilddao.vercel.app/',
    hackathon: 'ETH Rome',
    award: 'Scaffold grant',
    date: 'Oct 2023',
  },
  {
    id: 'dashdao',
    title: 'DashDAO',
    description: 'An advanced DAO dashboard offering detailed insights into activities, votes, and operations for comprehensive management of decentralized organizations.',    emoji: '📊',
    githubLink: 'https://github.com/DashDAO/dao-dashboard',
    externalLink: 'https://dashdao.vercel.app',
    hackathon: 'ETHWarsaw',
    award: 'Top 5 finalist',
    date: 'Sep 2023',
  },
  {
    id: 'kyotoswap',
    title: 'KyotoSwap Smart Contracts',
    description: 'Contributed to the development and testing of the Lock Boost function for KyotoSwap, enhancing its smart contract capabilities.',
    emoji: '🔄',
    githubLink: 'https://bscscan.com/address/0x2a1318f15344fba7758482bd74489aa9a90ad03f#code',
    externalLink: 'https://www.kyotoswap.io/',
    hackathon: 'Open Source',
    date: 'Aug 2023',
  },
  {
    id: 'ginger-security',
    title: 'Ginger Security Frontend Development',
    description: 'Handled the frontend development for Ginger Security, creating responsive and user-friendly components to improve overall design and UX.',
    emoji: '🔒',
    externalLink: 'https://gingersec.xyz/',
    hackathon: 'Client project',
    date: 'July 2023',
  }
];