export const projectsData = [
  {
    id: 'cook-some-hooks',
    title: 'Cook some hooks',
    description: 'A v4 hook generator leveraging generative AI where users can select a pair, introduce a prompt, get the hook generated, deployed and verified in a couple clicks.',
    emoji: '👨‍🍳',
    externalLink: 'https://ethglobal.com/showcase/cook-some-hooks-9e8yv',
    hackathon: 'ETH Global Brussels',
    award: 'Finalist top 10 project',
    date: 'March 2024',
  },
  {
    id: 'popkorn',
    title: 'POPKORN',
    description: 'Proof Of Private Key Ownership Requiring Nothing, removing the need for signatures to proof ownership of a wallet.',
    emoji: '🍿',
    githubLink: 'https://github.com/private-key-black-box/frontend',
    externalLink: 'https://devfolio.co/projects/popkorn-61b7',
    hackathon: 'zkKrakow',
    award: '1st place Mina',
    date: 'May 2024',
  },
  {
    id: 'endorsis',
    title: 'Endorsis',
    description: 'Endorsis -- a private platform for event feedback management.',
    emoji: '📝',
    githubLink: 'https://github.com/Endorsis/Endorsis',
    externalLink: 'https://demo-starter-frontend-git-fronttanguy-cleanerzkps-projects.vercel.app/#/',
    hackathon: 'ETHDam\'24',
    award: 'Oasis grant',
    date: 'April 2024',
  },
  {
    id: 'ghoflow',
    title: 'GhoFlow',
    description: 'Payment widget + smart contacts to streamline creation of superfluid streams of GHO, by depositing ETH or ERC20 token. From 6 transactions to 1 (ETH) or 2 (Token approval).',
    emoji: '💸',
    externalLink: 'https://ethglobal.com/showcase/ghoflow-e8y2c',
    hackathon: 'LFGHO - async hackathon',
    date: 'Jan 2024',
  },
  {
    id: 'spot-instance-comparison',
    title: 'Spot Instance Price Comparison',
    description: 'An automated tool for collecting and comparing spot pricing data from major cloud providers, leading to more efficient infrastructure spending.',
    emoji: '💰',
    githubLink: 'https://github.com/cleanerzkp/spot-instance-comparison',
    hackathon: 'Client project',
    date: 'Feb 2024',
  },
  {
    id: 'dog',
    title: 'DOG (Def Original Goal)',
    description: 'A standout project at ETHGlobal, winning the Threshold Network Best Use Prize, Scroll Bounty, and Worldcoin Pool Prize.',
    emoji: '🐕',
    githubLink: 'https://github.com/0xPetra/zkCreditScore',
    externalLink: 'https://ethglobal.com/showcase/dog-gipja',
    hackathon: 'ETHGlobal Showcase',
    date: 'Nov 2023',
  },
  {
    id: 'rebuilddao',
    title: 'RebuildDAO',
    description: 'An innovative DAO project, claiming the BuildGuild bounty and the SpagettETH bounty at ETH Rome.',
    emoji: '🏛️',
    githubLink: 'https://github.com/orgs/RebuildDAO/repositories',
    externalLink: 'https://rebuilddao.vercel.app/',
    hackathon: 'ETH Rome',
    date: 'Oct 2023',
  },
  {
    id: 'dashdao',
    title: 'DashDAO',
    description: 'Awarded the ETHWarsaw Best Project Prize and Mantle bounty, in-depth DAO dashboard.',
    emoji: '📊',
    githubLink: 'https://github.com/DashDAO/dao-dashboard',
    externalLink: 'https://dashdao.vercel.app',
    hackathon: 'ETHWarsaw',
    date: 'Sep 2023',
  },
  {
    id: 'kyotoswap',
    title: 'KyotoSwap Smart Contracts',
    description: 'Contributed to the development of the Lock Boost function and tested it.',
    emoji: '🔄',
    githubLink: 'https://bscscan.com/address/0x2a1318f15344fba7758482bd74489aa9a90ad03f#code',
    externalLink: 'https://www.kyotoswap.io/',
    hackathon: 'Open Source',
    date: 'Aug 2023',
  },
  {
    id: 'ginger-security',
    title: 'Ginger Security Frontend Development',
    description: 'Handled frontend development, crafting responsive and user-friendly components, enhancing overall design and user experience.',
    emoji: '🔒',
    externalLink: 'https://gingersec.xyz/',
    hackathon: 'Client project',
    date: 'July 2023',
  }
];