export const projectsData = [
  {
    id: 'cook-some-hooks',
    title: 'Cook Some Hooks',
    description: 'Developed a Next.js application for generating Uniswap v4 hooks using generative AI, allowing users to easily create, deploy, and verify hooks in just a few clicks.',
    emoji: '👨‍🍳',
    externalLink: 'https://ethglobal.com/showcase/cook-some-hooks-9e8yv',
    hackathon: 'ETH Global Brussels',
    award: 'Finalist Top 10 Project',
    date: 'July 2024',
  },
  {
    id: 'garden-ecommerce-shop',
    title: 'Gardenening E-commerce Shop',
    description: 'Developed a Next.js and Shopify-based e-commerce platform for a gardening shop, featuring a sleek design, seamless shopping experience, and optimized checkout process.',
    emoji: '🌼',
    hackathon: 'Client Project',
    date: 'May 2024',
  },
  {
    id: 'spot-instance-comparison',
    title: 'Spot Instance Price Comparison',
    description: 'Built an automated tool using Node.js and Express to collect and compare spot pricing data from major cloud providers, optimizing infrastructure spending for clients.',
    emoji: '💰',
    githubLink: 'https://github.com/cleanerzkp/spot-instance-comparison',
    hackathon: 'Client Project',
    date: 'Feb 2024',
  },
  {
    id: 'ginger-security',
    title: 'Ginger Security Frontend Development',
    description: 'Led the frontend development of a security platform using React to create responsive and user-friendly components, improving overall design and user experience.',
    emoji: '🔒',
    externalLink: 'https://gingersec.xyz/',
    hackathon: 'Client Project',
    date: 'July 2023',
  },
];